# Site settings
title: James R. A. Davenport
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url:  "http://jradavenport.github.io" # "http://localhost:4000" #
twitter_username: jradavenport
github_username:  jradavenport
linkedin_username: jradavenport
#cv: "https://www.dropbox.com/s/9wan6osj4g4knqm/davenport.cv.pdf?dl=1"
#cv: "https://www.dropbox.com/s/r2xdam303rge7c9/davenport.cv.pdf?dl=1"
#cv: "https://www.dropbox.com/s/v1m5iek32a69434/davenport.cv.pdf?dl=1"
cv: "https://www.dropbox.com/s/du48mz4el33xr7m/davenport.cv_full.pdf?dl=1"
ads_link: "http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?return_req=no_params&author=Davenport,%20James%20R.%20A.&db_key=PRE"
mastodon:
- username: jradavenport
- instance: mastodon.social 

# Build settings
# markdown: kramdown
